### ISSUE TITLE
What version of zeek did you use

### ISSUE THREAD

**Issue by dsussens** [WqyJh/zeek-netmap#1]
I have followed the instructions for installing your zeek-netmap plugin.  I start lb as follows:
# lb -i ens1f0 -p zeek:6
265.392496 main [590] interface is ens1f0
265.460937 main [697] successfully opened netmap:ens1f0
265.460949 main [768] opening pipe named netmap:zeek{0/xT@1
265.461141 main [783] successfully opened pipe #1 netmap:zeek{0/xT@1 (tx slots: 1024)
265.461150 main [788] zerocopy enabled
265.461154 main [768] opening pipe named netmap:zeek{1/xT@1
265.461191 main [783] successfully opened pipe #2 netmap:zeek{1/xT@1 (tx slots: 1024)
265.461197 main [788] zerocopy enabled
265.461199 main [768] opening pipe named netmap:zeek{2/xT@1
265.461232 main [783] successfully opened pipe #3 netmap:zeek{2/xT@1 (tx slots: 1024)
265.461244 main [788] zerocopy enabled
265.461248 main [768] opening pipe named netmap:zeek{3/xT@1
265.461280 main [783] successfully opened pipe #4 netmap:zeek{3/xT@1 (tx slots: 1024)
265.461286 main [788] zerocopy enabled
265.461289 main [768] opening pipe named netmap:zeek{4/xT@1
265.461320 main [783] successfully opened pipe #5 netmap:zeek{4/xT@1 (tx slots: 1024)
265.461326 main [788] zerocopy enabled
265.461328 main [768] opening pipe named netmap:zeek{5/xT@1
265.461368 main [783] successfully opened pipe #6 netmap:zeek{5/xT@1 (tx slots: 1024)
265.461376 main [788] zerocopy enabled

When I run zeek I get the following:
#zeek -i netmap::zeek
fatal error: type of packet source 'netmap' not recognized, or mode not supported.

Can you share your build process and the version of Zeek that you used please?  

Thank you

**Comment by WqyJh** [comment]
Hi,
My zeek version is 3.1.2 and I use zeek's `node.cfg` to configure zeek-netmap and use zeekctl to  start zeek.
```ini
[manager]
type=manager
host=localhost

[proxy-1]
type=proxy
host=localhost

[worker-1]
type=worker
host=localhost
lb_method=custom
lb_procs=2
interface=netmap::zeek
pin_cpus=0,1
```
Start lb.
```bash
$ lb -i eth3 -p zeek:2                                                                                                               
009.661979 main [588] interface is eth3
009.751695 main [702] successfully opened netmap:eth3 (tx rings: 256)
009.751717 main [774] opening pipe named netmap:zeek{0/xT@1
009.756276 nm_mmap [987] do not mmap, inherit from parent
009.756300 main [789] successfully opened pipe #1 netmap:zeek{0/xT@1 (tx slots: 1024)
009.756303 main [794] zerocopy enabled
009.756307 main [774] opening pipe named netmap:zeek{1/xT@1
009.756362 nm_mmap [987] do not mmap, inherit from parent
009.756367 main [789] successfully opened pipe #2 netmap:zeek{1/xT@1 (tx slots: 1024)
009.756369 main [794] zerocopy enabled
```
Start zeek cluster
```bash
[ZeekControl] > install
creating policy directories ...
installing site policies ...
generating standalone-layout.zeek ...
generating local-networks.zeek ...
generating zeekctl-config.zeek ...
generating zeekctl-config.sh ...
[ZeekControl] > start
starting manager ...
starting proxy ...
starting workers ...
[ZeekControl] > exit
```
Reference to [Basic Cluster Configuration](https://docs.zeek.org/en/v3.1.2/configuration/index.html#basic-cluster-configuration).

The processes started by zeekctl
```bash
$ ps axu | grep zeek
root     10300  0.0  0.1 189468  2992 pts/1    S+   13:36   0:00 sudo lb -i eth3 -p zeek:2
root     10301  0.2  0.0 421664   752 pts/1    Sl+  13:36   0:00 lb -i eth3 -p zeek:2
root     10557  0.0  0.0 106116  1332 ?        S    13:37   0:00 /bin/bash /usr/local/zeek/share/zeekctl/scripts/run-zeek -1 -U .status -p zeekctl -p zeekctl-live -p local -p manager local.zeek zeekctl base/frameworks/cluster zeekctl/auto
root     10563  6.1  4.7 985808 90992 ?        Rl   13:37   0:01 /usr/local/zeek/bin/zeek -U .status -p zeekctl -p zeekctl-live -p local -p manager local.zeek zeekctl base/frameworks/cluster zeekctl/auto
root     10756  0.0  0.0 106116  1336 ?        S    13:37   0:00 /bin/bash /usr/local/zeek/share/zeekctl/scripts/run-zeek -1 -U .status -p zeekctl -p zeekctl-live -p local -p proxy-1 local.zeek zeekctl base/frameworks/cluster zeekctl/auto
root     10762  7.3  4.5 605132 87216 ?        Sl   13:37   0:01 /usr/local/zeek/bin/zeek -U .status -p zeekctl -p zeekctl-live -p local -p proxy-1 local.zeek zeekctl base/frameworks/cluster zeekctl/auto
root     11106  0.0  0.0 106116  1336 ?        S    13:37   0:00 /bin/bash /usr/local/zeek/share/zeekctl/scripts/run-zeek 0 -i netmap::zeek}0 -U .status -p zeekctl -p zeekctl-live -p local -p worker-1-1 local.zeek zeekctl base/frameworks/cluster zeekctl/auto
root     11111  0.0  0.0 106116  1336 ?        S    13:37   0:00 /bin/bash /usr/local/zeek/share/zeekctl/scripts/run-zeek 1 -i netmap::zeek}1 -U .status -p zeekctl -p zeekctl-live -p local -p worker-1-2 local.zeek zeekctl base/frameworks/cluster zeekctl/auto
root     11121 18.9  4.6 940148 89352 ?        Rl   13:37   0:03 /usr/local/zeek/bin/zeek -i netmap::zeek}0 -U .status -p zeekctl -p zeekctl-live -p local -p worker-1-1 local.zeek zeekctl base/frameworks/cluster zeekctl/auto
root     11123 22.2  4.5 940104 87304 ?        Rl   13:37   0:04 /usr/local/zeek/bin/zeek -i netmap::zeek}1 -U .status -p zeekctl -p zeekctl-live -p local -p worker-1-2 local.zeek zeekctl base/frameworks/cluster zeekctl/auto
root     11210  0.0  0.0 103336   888 pts/0    S+   13:37   0:00 grep zeek
```

Therefore, you can start two zeek worker manually in the following way.

```bash
zeek -i netmap::zeek}0 -p worker-1-1
zeek -i netmap::zeek}1 -p worker-1-2
```

However, zeekctl is recommended.

**Comment by dsussens** [comment]
I was able to install your netmap plugin manually, without using the Zeek
Package Manager.

It is working as expected.  Thank you for providing this git repository.
